FROM node:lts
WORKDIR /workspace
RUN npm install -g create-react-app
# RUN npm install axios
# RUN npm install react-router-dom --save
# RUN npm install --save @types/react-router-dom

# CTRL±C -> docker compose up
