version: '3'

services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/workspace
    tty: true
  
  fastapi:
    container_name: fastapi
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT_FASTAPI=${PORT_FASTAPI}
        - UID
    ports:
      - "${PORT_FASTAPI}:${PORT_FASTAPI}"
    volumes:
      - ./backend:/workspace
    tty: true

